// ── Mots-clés multilingues pour la recherche emoji (EmojiPicker.jsx) ──────────
// Générés depuis les annotations officielles Unicode CLDR (unicode-org/cldr-json,
// cldr-annotations-full, champ "tts" = nom court), une entrée par emoji utilisé
// dans EMOJI_CATS. Chaque valeur concatène le nom dans les 6 langues supportées
// par l'app (i18n.js SUPPORTED_LANGS = fr, en, es, de, ru, zh) : la recherche
// fonctionne quelle que soit la langue tapée, indépendamment de la langue
// actuellement affichée dans l'app — "stalker" ou l'équivalent russe/chinois
// d'un mot retrouveraient tous les deux le même emoji, par exemple.
// Généré programmatiquement à partir des fichiers CLDR récupérés (PAS retapé à
// la main) — pour ne jamais introduire de traduction inventée. Si EMOJI_CATS
// (EmojiPicker.jsx) gagne de nouveaux emojis, ce fichier doit être régénéré pour
// les couvrir ; à défaut ils restent cliquables normalement, la recherche
// retombant simplement sur aucun mot-clé pour eux.
export const EMOJI_KEYWORDS = {
  "🎮": "jeu vidéo video game mando de videoconsola Gamepad видеоигры 游戏手柄",
  "🕹️": "manette de jeu joystick joystick Joystick джойстик 游戏操控杆",
  "👾": "monstre de l’espace alien monster monstruo alienígena Computerspiel-Monster космический монстр 外星怪物",
  "🎲": "dés game die dado Spielwürfel игральная кость 骰子",
  "🃏": "carte Joker joker comodín Jokerkarte джокер 大小王",
  "🧩": "pièce de puzzle puzzle piece pieza de puzle Puzzleteil пазл 拼图",
  "🎯": "dans le mille bullseye diana Darts мишень 正中靶心的飞镖",
  "🏹": "arc et flèche bow and arrow arco y flecha Pfeil und Bogen лук со стрелой 弓和箭",
  "⚔️": "épées croisées crossed swords espadas cruzadas gekreuzte Schwerter скрещенные мечи 交叉放置的剑",
  "🗡️": "dague dagger puñal Dolch кинжал 匕首",
  "🛡️": "bouclier shield escudo Schutzschild щит 盾牌",
  "🪃": "boomerang boomerang bumerán Bumerang бумеранг 回旋镖",
  "🔫": "pistolet à eau water pistol pistola de agua Wasserpistole водяной пистолет 水枪",
  "💣": "bombe bomb bomba Bombe бомба 炸弹",
  "🧲": "aimant magnet imán Magnet магнит 磁铁",
  "🪄": "baguette magique magic wand varita mágica Zauberstab волшебная палочка 魔棒",
  "🎪": "chapiteau circus tent carpa de circo Zirkuszelt цирковой шатер 马戏团帐篷",
  "🎡": "grande roue ferris wheel noria de feria Riesenrad колесо обозрения 摩天轮",
  "🎠": "cheval de manège carousel horse caballo de tiovivo Karussellpferd лошадь на карусели 旋转木马",
  "🎢": "montagnes russes roller coaster montaña rusa Achterbahn американские горки 过山车",
  "🏆": "trophée trophy trofeo Pokal кубок 奖杯",
  "🥇": "médaille d’or 1st place medal medalla de oro Goldmedaille золотая медаль 金牌",
  "🥈": "médaille d’argent 2nd place medal medalla de plata Silbermedaille серебряная медаль 银牌",
  "🥉": "médaille de bronze 3rd place medal medalla de bronce Bronzemedaille бронзовая медаль 铜牌",
  "🎖️": "médaille militaire military medal medalla militar Militärorden военная медаль 军功章",
  "🏅": "médaille sportive sports medal medalla deportiva Sportmedaille спортивная медаль 奖牌",
  "⭐": "étoile star estrella weißer mittelgroßer Stern желтая звезда 星星",
  "🌟": "étoile brillante glowing star estrella brillante funkelnder Stern сияющая звезда 闪亮的星星",
  "💫": "étourdissement dizzy símbolo de mareo schwindlig кружащаяся звезда 头晕",
  "✨": "étincelles sparkles chispas funkelnde Sterne блестки 闪亮",
  "💥": "explosion collision colisión Zusammenstoß взрыв 爆炸",
  "🔥": "feu fire fuego Feuer огонь 火焰",
  "❄️": "flocon snowflake copo de nieve Schneeflocke снежинка 雪花",
  "⚡": "haute tension high voltage alto voltaje Hochspannung высокое напряжение 高压",
  "🌊": "vague water wave ola de mar Welle волна 浪花",
  "💎": "pierre précieuse gem stone piedra preciosa Edelstein драгоценный камень 宝石",
  "💍": "bague ring anillo Ring кольцо 戒指",
  "👑": "couronne crown corona Krone корона 皇冠",
  "🎗️": "ruban de mémoire reminder ribbon lazo conmemorativo Gedenkschleife памятная лента 提示丝带",
  "🏁": "drapeau à damier chequered flag bandera de cuadros Zielflagge клетчатый флаг 黑白方格旗",
  "📋": "porte-bloc clipboard portapapeles Klemmbrett планшет с зажимом 剪贴板",
  "📌": "punaise pushpin chincheta Reißzwecke канцелярская кнопка 图钉",
  "📍": "épingle round pushpin chincheta redonda Stecknadel канцелярская кнопка с шариком 圆图钉",
  "🔖": "marque-page bookmark marcapáginas Lesezeichen закладка 书签",
  "📎": "trombone paperclip clip Büroklammer скрепка 回形针",
  "🖇️": "trombones linked paperclips clips unidos verhakte Büroklammern скрепки 连起来的两个回形针",
  "📏": "règle straight ruler regla Lineal линейка 直尺",
  "📐": "équerre triangular ruler escuadra dreieckiges Lineal линейка-треугольник 三角尺",
  "✏️": "crayon pencil lápiz Bleistift карандаш 铅笔",
  "🖊️": "stylo pen bolígrafo Kugelschreiber шариковая ручка 笔",
  "🖋️": "stylo plume fountain pen estilográfica Füllhalter перьевая ручка 钢笔",
  "📝": "mémo memo cuaderno de notas Papier und Bleistift заметка 备忘录",
  "📄": "page page facing up página hacia arriba Vorderseite eines Blattes страница 文件",
  "📃": "page enroulée page with curl página doblada teilweise eingerolltes Blatt страница с загибом 带卷边的页面",
  "📑": "signets bookmark tabs marcadores Pagemarker стикеры-закладки 标签页",
  "📊": "graphiques à barres bar chart gráfico de barras Balkendiagramm гистограмма 条形图",
  "📈": "graphique en hausse chart increasing gráfica de evolución ascendente Aufwärtstrend диаграмма роста 趋势向上的图表",
  "📉": "graphique en baisse chart decreasing gráfica de evolución descendente Abwärtstrend диаграмма падения 趋势向下的图表",
  "🗂️": "intercalaires card index dividers separador de fichas Karteireiter маркированные папки 索引分隔文件夹",
  "🗃️": "boîte à dossiers card file box archivador de tarjetas Karteikasten картотека 卡片盒",
  "💼": "porte-documents briefcase maletín Aktentasche портфель 公文包",
  "🗄️": "meuble à dossiers file cabinet archivador Aktenschrank архивный шкаф 文件柜",
  "🖥️": "ordinateur de bureau desktop computer ordenador de sobremesa Desktopcomputer компьютер 台式电脑",
  "💻": "ordinateur portable laptop ordenador portátil Laptop ноутбук 笔记本电脑",
  "⌨️": "clavier keyboard teclado Tastatur клавиатура 键盘",
  "🖱️": "souris d’ordinateur computer mouse ratón de ordenador Computermaus мышка 电脑鼠标",
  "🖨️": "imprimante printer impresora Drucker принтер 打印机",
  "📱": "téléphone portable mobile phone teléfono móvil Mobiltelefon мобильный телефон 手机",
  "☎️": "téléphone telephone teléfono Telefon телефон 电话",
  "📞": "combiné téléphonique telephone receiver auricular de teléfono Telefonhörer телефонная трубка 电话听筒",
  "📟": "bipeur pager busca Pager пейджер 寻呼机",
  "📠": "fax fax machine máquina de fax Faxgerät факс 传真机",
  "🔍": "loupe orientée à gauche magnifying glass tilted left lupa orientada hacia la izquierda Lupe nach links лупа, наклоненная влево 左斜的放大镜",
  "🔎": "loupe orientée à droite magnifying glass tilted right lupa orientada hacia la derecha Lupe nach rechts лупа, наклоненная вправо 右斜的放大镜",
  "🔬": "microscope microscope microscopio Mikroskop микроскоп 显微镜",
  "🔭": "télescope telescope telescopio Teleskop телескоп 望远镜",
  "📡": "antenne satellite satellite antenna antena de satélite Satellitenschüssel спутниковая антенна 卫星天线",
  "🛰️": "satellite satellite satélite Satellit спутник 卫星",
  "⚙️": "roue dentée gear engranaje Zahnrad шестеренка 齿轮",
  "🔧": "clé à molette wrench llave inglesa Schraubenschlüssel гаечный ключ 扳手",
  "💾": "disquette floppy disk disquete Diskette дискета 软盘",
  "💿": "CD optical disk disco óptico CD CD 光盘",
  "📀": "DVD dvd disco DVD DVD DVD DVD",
  "🔌": "câble avec fiche électrique electric plug enchufe eléctrico Netzstecker вилка 电源插头",
  "🔋": "pile battery pila Batterie батарейка 电池",
  "🧮": "abaque abacus ábaco Abakus счеты 算盘",
  "🤖": "robot robot robot Roboter робот 机器人",
  "🔨": "marteau hammer martillo Hammer молоток 锤子",
  "🪛": "tournevis screwdriver destornillador Schraubenzieher отвертка 螺丝刀",
  "🪚": "scie carpentry saw sierra de carpintería Handsäge пила по дереву 木工锯",
  "🪓": "hache axe hacha Axt топор 斧头",
  "⛏️": "pioche pick pico Pickel кирка 铁镐",
  "🧰": "boîte à outils toolbox caja de herramientas Werkzeugkasten ящик для инструментов 工具箱",
  "🔩": "vis et écrou nut and bolt tornillo y tuerca Mutter und Schraube болт и гайка 螺母与螺栓",
  "🧱": "brique brick ladrillo Ziegelstein кирпичи 砖",
  "🪜": "échelle ladder escalera Leiter лестница 梯子",
  "✂️": "ciseaux scissors tijeras Schere ножницы 剪刀",
  "🪣": "seau bucket cubo Eimer ведро 桶",
  "🧯": "extincteur fire extinguisher extintor Feuerlöscher огнетушитель 灭火器",
  "🗜️": "serre-joint clamp tornillo de banco Schraubzwinge компрессор 夹钳",
  "🪝": "crochet hook gancho Haken крюк 挂钩",
  "🔗": "chaînons link eslabón Linksymbol гиперссылка 链接",
  "✅": "bouton coché check mark button botón de marca de verificación weißes Häkchen белая галочка 勾号按钮",
  "❌": "croix cross mark marca de cruz Kreuzzeichen крестик 叉号",
  "⚠️": "symbole d’avertissement warning advertencia Warnung значок предупреждения 警告",
  "🚫": "symbole d’interdiction prohibited prohibido Verboten запрещено 禁止",
  "⛔": "sens interdit no entry dirección prohibida Zutritt verboten въезд запрещен 禁止通行",
  "🔴": "disque rouge red circle círculo rojo roter Punkt красный круг 红色圆",
  "🟠": "disque orange orange circle círculo naranja oranger Punkt оранжевый круг 橙色圆",
  "🟡": "disque jaune yellow circle círculo amarillo gelber Punkt желтый круг 黄色圆",
  "🟢": "disque vert green circle círculo verde grüner Punkt зеленый круг 绿色圆",
  "🔵": "disque bleu blue circle círculo azul blauer Punkt голубой круг 蓝色圆",
  "🟣": "disque violet purple circle círculo morado lila Punkt фиолетовый круг 紫色圆",
  "⚫": "disque noir black circle círculo negro schwarzer Punkt черный круг 黑色圆",
  "⚪": "disque blanc white circle círculo blanco weißer Punkt белый круг 白色圆",
  "🟤": "disque marron brown circle círculo marrón brauner Punkt коричневый круг 棕色圆",
  "🔶": "grand losange orange large orange diamond rombo naranja grande große orangefarbene Raute большой оранжевый ромб 橙色大菱形",
  "🔷": "grand losange bleu large blue diamond rombo azul grande große blaue Raute большой голубой ромб 蓝色大菱形",
  "🔸": "petit losange orange small orange diamond rombo naranja pequeño kleine orangefarbene Raute небольшой оранжевый ромб 橙色小菱形",
  "🔹": "petit losange bleu small blue diamond rombo azul pequeño kleine blaue Raute небольшой голубой ромб 蓝色小菱形",
  "💤": "endormi ZZZ símbolo de sueño Schlafen сон 睡着",
  "⏳": "sablier avec sable qui coule hourglass not done reloj de arena con tiempo laufende Sanduhr время пошло 沙正往下流的沙漏",
  "🔔": "cloche bell campana Glocke колокольчик 铃铛",
  "🔕": "alarme désactivée bell with slash campana con signo de cancelación durchgestrichene Glocke перечеркнутый колокольчик 禁止响铃",
  "📣": "porte-voix megaphone megáfono Megafon мегафон 扩音器",
  "📢": "haut-parleur loudspeaker altavoz de mano Lautsprecher громкоговоритель 喇叭",
  "🚨": "gyrophare police car light luces de policía Polizeilicht мигалка 警车灯",
  "🚩": "drapeau triangulaire triangular flag bandera triangular Wimpel треугольный флаг 三角旗",
  "🏴": "drapeau noir black flag bandera negra schwarze Flagge черный флаг 黑旗",
  "🏳️": "drapeau blanc white flag bandera blanca weiße Flagge белый флаг 白旗",
  "🚀": "fusée rocket cohete Rakete ракета 火箭",
  "💡": "ampoule light bulb bombilla Glühbirne лампочка 灯泡",
  "🔦": "torche flashlight linterna Taschenlampe фонарик 手电筒",
  "🕯️": "bougie candle vela Kerze свеча 蜡烛",
  "🔒": "cadenas fermé locked candado cerrado geschlossenes Schloss закрытый замок 合上的锁",
  "🔓": "cadenas ouvert unlocked candado abierto offenes Schloss открытый замок 打开的锁",
  "🔑": "clé key llave Schlüssel ключ 钥匙",
  "🗝️": "clé ancienne old key llave antigua alter Schlüssel старинный ключ 老式钥匙",
  "🛜": "sans fil wireless wifi WLAN беспроводная сеть 无线",
  "🌍": "globe tourné sur l’Afrique et l’Europe globe showing Europe-Africa globo terráqueo mostrando Europa y África Globus mit Europa und Afrika Европа и Африка на земном шаре 地球上的欧洲非洲",
  "🌲": "conifère evergreen tree árbol de hoja perenne Nadelbaum елка 松树",
  "🌳": "arbre à feuilles caduques deciduous tree árbol de hoja caduca Laubbaum дерево 落叶树",
  "🌴": "palmier palm tree palmera Palme пальма 棕榈树",
  "🌵": "cactus cactus cactus Kaktus кактус 仙人掌",
  "🌾": "plant de riz sheaf of rice espiga de arroz Reisähre колос 稻子",
  "🍀": "trèfle à quatre feuilles four leaf clover trébol de cuatro hojas Glücksklee четырехлистный клевер 四叶草",
  "🌸": "fleur de cerisier cherry blossom flor de cerezo Kirschblüte цветок вишни 樱花",
  "🌺": "hibiscus hibiscus flor de hibisco Hibiskus гибискус 芙蓉",
  "🌻": "tournesol sunflower girasol Sonnenblume подсолнух 向日葵",
  "🌹": "rose rose rosa Rose роза 玫瑰",
  "🍁": "feuille d’érable maple leaf hoja de arce Ahornblatt кленовый лист 枫叶",
  "🍂": "feuille morte fallen leaf hojas caídas Laub падающие листья 落叶",
  "🍃": "feuille virevoltante leaf fluttering in wind hojas revoloteando al viento Blätter im Wind листья на ветру 风吹叶落",
  "🌿": "feuille herb hierba Kräuter веточка 药草",
  "☘️": "trèfle shamrock trébol Kleeblatt трилистник 三叶草",
  "🪨": "rocher rock piedra Felsen камень 岩石",
  "🌙": "croissant de lune crescent moon luna Mondsichel полумесяц 弯月",
  "☀️": "soleil sun sol Sonne солнце 太阳",
  "⛅": "soleil derrière les nuages sun behind cloud sol detrás de una nube Sonne hinter Wolke солнце за облаками 阴",
  "🎨": "palette de peinture artist palette paleta de pintor Mischpalette палитра с красками 调色盘",
  "🖌️": "pinceau paintbrush pincel Pinsel кисточка 画笔",
  "📸": "appareil photo avec flash camera with flash cámara con flash Fotoapparat mit Blitz фотоаппарат со вспышкой 开闪光灯的相机",
  "🎬": "clap clapper board claqueta Filmklappe хлопушка-нумератор 场记板",
  "🎵": "note de musique musical note nota musical Musiknote нота 音符",
  "🎶": "notes de musique musical notes notas musicales Musiknoten ноты 多个音符",
  "🎸": "guitare guitar guitarra Gitarre гитара 吉他",
  "🎹": "piano musical keyboard teclado musical Klaviatur клавишные 音乐键盘",
  "🎺": "trompette trumpet trompeta Trompete труба 小号",
  "🎻": "violon violin violín Geige скрипка 小提琴",
  "🥁": "batterie drum tambor Trommel барабан 鼓",
  "🎤": "micro microphone micrófono Mikrofon микрофон 麦克风",
  "🎧": "casque headphone auricular Kopfhörer наушники 耳机",
  "🎭": "spectacle vivant performing arts máscaras de teatro Masken маски 表演艺术",
  "💬": "bulle de parole speech balloon bocadillo de diálogo Sprechblase mit drei Punkten облачко с многоточием 话语气泡",
  "💭": "bulle de pensée thought balloon bocadillo de pensamiento Gedankenblase облачко с мыслями 内心活动气泡",
  "🗯️": "bulle colère droite right anger bubble bocadillo de enfado por la derecha Sprechblase für wütende Aussage rechts гневное облачко 愤怒话语气泡",
  "❤️": "cœur rouge red heart corazón rojo rotes Herz алое сердце 红心",
  "🧡": "cœur orange orange heart corazón naranja oranges Herz оранжевое сердце 橙心",
  "💛": "cœur jaune yellow heart corazón amarillo gelbes Herz желтое сердце 黄心",
  "💚": "cœur vert green heart corazón verde grünes Herz зеленое сердце 绿心",
  "💙": "cœur bleu blue heart corazón azul blaues Herz синее сердце 蓝心",
  "💜": "cœur violet purple heart corazón morado lila Herz фиолетовое сердце 紫心",
  "🖤": "cœur noir black heart corazón negro schwarzes Herz черное сердце 黑心",
  "🤍": "cœur blanc white heart corazón blanco weißes Herz белое сердце 白心",
  "💕": "deux cœurs two hearts dos corazones zwei Herzen два сердца 两颗心",
  "💞": "cœurs qui tournent revolving hearts corazones giratorios kreisende Herzen вращающиеся сердца 舞动的心",
  "💓": "cœur battant beating heart corazón latiendo schlagendes Herz пульсирующее сердце 心跳",
  "💗": "cœur grandissant growing heart corazón creciente wachsendes Herz растущее сердце 搏动的心",
  "💖": "cœur étincelant sparkling heart corazón brillante funkelndes Herz сверкающее сердце 闪亮的心",
  "💘": "cœur et flèche heart with arrow corazón con flecha Herz mit Pfeil сердце, пронзенное стрелой 心中箭了",
  "💝": "cœur avec ruban heart with ribbon corazón con lazo Herz mit Schleife сердце с лентой 系有缎带的心",
  "👍": "pouce vers le haut thumbs up pulgar hacia arriba Daumen hoch большой палец вверх 拇指向上",
  "👎": "pouce vers le bas thumbs down pulgar hacia abajo Daumen runter большой палец вниз 拇指向下",
  "🧠": "cerveau brain cerebro Gehirn мозг 脑",
  "👀": "yeux eyes ojos Augen глаза 双眼",
  "💪": "biceps contracté flexed biceps bíceps flexionado angespannter Bizeps бицепс 肌肉",
  "🤝": "poignée de main handshake apretón de manos Handschlag рукопожатие 握手",
  "🙌": "mains levées raising hands manos levantadas celebrando zwei erhobene Handflächen ура 举双手",
  "👏": "applaudissements clapping hands manos aplaudiendo klatschende Hände аплодисменты 鼓掌",
  "🤜": "poing à droite right-facing fist puño hacia la derecha Faust nach rechts кулак вправо 朝右的拳头",
  "🏃": "personne qui court person running persona corriendo laufende Person человек бежит 跑步者",
  "🧑‍💻": "informaticien (tous genres) technologist profesional de la tecnología IT-Experte/IT-Expertin инженер 程序员",
  "👷": "personnel du bâtiment construction worker profesional de la construcción Bauarbeiter(in) строитель 建筑工人",
  "🧑‍🎨": "artiste artist artista Künstler(in) художник 艺术家",
  "🦁": "tête de lion lion león Löwe морда льва 狮子",
  "🐺": "loup wolf lobo Wolf морда волка 狼",
  "🦊": "renard fox zorro Fuchs морда лисицы 狐狸",
  "🐉": "dragon dragon dragón Drache дракон 龙",
  "🦄": "licorne unicorn unicornio Einhorn голова единорога 独角兽",
  "👻": "fantôme ghost fantasma Gespenst привидение 鬼",
  "💀": "crâne skull calavera Totenkopf череп 头骨",
  "👽": "alien alien alienígena Außerirdischer инопланетянин 外星人",
};
